[package]
name = "linkedlist"
version = "0.1.0"
authors = ["李鸿章 <poodll@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
